// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjvQQXtNDCdlSACyZGcZc_AmKBcRvS_Vg',
    appId: '1:1026057941079:web:10445089f7f75bad8db312',
    messagingSenderId: '1026057941079',
    projectId: 'xsat-2cf9e',
    authDomain: 'xsat-2cf9e.firebaseapp.com',
    storageBucket: 'xsat-2cf9e.firebasestorage.app',
    measurementId: 'G-J3Z5PGH8BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy9KY7weiI9NgoIl-N3m37s_HlB9eydg0',
    appId: '1:1026057941079:android:82aa2c59a344cde98db312',
    messagingSenderId: '1026057941079',
    projectId: 'xsat-2cf9e',
    storageBucket: 'xsat-2cf9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnK3eEcpl15RuUBRiTw-MEzz9nBFUvByE',
    appId: '1:1026057941079:ios:d705a775201c07ec8db312',
    messagingSenderId: '1026057941079',
    projectId: 'xsat-2cf9e',
    storageBucket: 'xsat-2cf9e.firebasestorage.app',
    iosClientId: '1026057941079-cakp6md06b2rluq82206n6mdpugcibi1.apps.googleusercontent.com',
    iosBundleId: 'com.xaffan.xsat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnK3eEcpl15RuUBRiTw-MEzz9nBFUvByE',
    appId: '1:1026057941079:ios:d705a775201c07ec8db312',
    messagingSenderId: '1026057941079',
    projectId: 'xsat-2cf9e',
    storageBucket: 'xsat-2cf9e.firebasestorage.app',
    iosClientId: '1026057941079-cakp6md06b2rluq82206n6mdpugcibi1.apps.googleusercontent.com',
    iosBundleId: 'com.xaffan.xsat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjvQQXtNDCdlSACyZGcZc_AmKBcRvS_Vg',
    appId: '1:1026057941079:web:37cfb87dda39aa028db312',
    messagingSenderId: '1026057941079',
    projectId: 'xsat-2cf9e',
    authDomain: 'xsat-2cf9e.firebaseapp.com',
    storageBucket: 'xsat-2cf9e.firebasestorage.app',
    measurementId: 'G-VNJ2GQCWJW',
  );
}
