# .github/workflows/release.yml
name: Android Release Only

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: xsat

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build apk --release
      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk ${{ env.PROJECT_NAME }}-Android.apk
      - name: Upload Android Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-Build
          path: ${{ env.PROJECT_NAME }}-Android.apk
