# .github/workflows/release.yml

name: Auto Release on Push

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches:
      - main

# Environment variables to use in the workflow
env:
  PROJECT_NAME: my_cool_app # TODO: Change this to your project's name

jobs:
  #---------------------------------------------------#
  #                 PLATFORM BUILDS                   #
  # All build jobs run in parallel to save time.      #
  #---------------------------------------------------#
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build apk --release
      - name: Upload Android Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-Build
          path: build/app/outputs/flutter-apk/app-release.apk

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - uses: subosito/flutter-action@v2
      - run: flutter build linux --release
      - run: tar -czvf ${{ env.PROJECT_NAME }}-Linux.tar.gz -C build/linux/x64/release/bundle .
      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux-Build
          path: ${{ env.PROJECT_NAME }}-Linux.tar.gz

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter build windows --release
      - run: Compress-Archive -Path build/windows/x64/runner/Release -DestinationPath ${{ env.PROJECT_NAME }}-Windows.zip
      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: ${{ env.PROJECT_NAME }}-Windows.zip

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter build macos --release
      - run: hdiutil create -fs HFS+ -srcfolder build/macos/Build/Products/Release/${{ env.PROJECT_NAME }}.app -volname "${{ env.PROJECT_NAME }}" ${{ env.PROJECT_NAME }}-macOS.dmg
      - name: Upload macOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-Build
          path: ${{ env.PROJECT_NAME }}-macOS.dmg

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter build ipa --release --no-codesign
      - name: Upload iOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Build
          path: build/ios/ipa/*.ipa

  #---------------------------------------------------#
  #             CREATE & PUBLISH RELEASE              #
  # This job runs after all builds, gathers the       #
  # artifacts, and creates a single release.          #
  #---------------------------------------------------#
  create-and-publish-release:
    name: Create & Publish Release
    runs-on: ubuntu-latest
    # This job depends on all the build jobs completing
    needs: [build-android, build-linux, build-windows, build-macos, build-ios]
    # This ensures the job runs even if some build jobs failed
    if: success() || failure()
    steps:
      - name: Generate Release Tag
        id: generate_tag
        run: echo "TAG=release-$(date +'%Y%m%d-%H%M')-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          # Destination path for all downloaded artifacts
          path: artifacts

      - name: List downloaded files for debugging
        run: ls -R artifacts

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          # This creates a new release using the generated tag
          tag_name: ${{ env.TAG }}
          name: "Auto Release ${{ env.TAG }}"
          body: |
            Automatic release generated from commit ${{ github.sha }}.
            
            **Note:** Some build files may be missing if their corresponding build job failed.
          # This uploads all files from all subdirectories inside 'artifacts'
          files: artifacts/**/*
